# 스웨거 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# 전체 API 그룹 설정 (선택적)
  api-docs:
    groups:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/day_check?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comment : true
    show-sql: true
  
  task:
    scheduling:
      pool:
        size: 5 # 스케줄러 스레드 풀 크기

  jwt:
    secret: "n1+cmO5jK90cDPDi1WPOpoJ7quq4mklwljZlUnc8s1ZQ0bqM0abQlCwF7hR+2Al/0XMTp4OXD5oN3tY4bAY8eA=="
    access-token-validity-in-seconds: 3600
    refresh-token-validity-in-seconds: 604800

  server:
    port: 8080

  mail:
    host: smtp.gmail.com
    port: 587
    username: tkdgns0056@gmail.com
    password: bhqe grhe hpql doeh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

#  mail:
##    host: smtp.gmail.com
#    host: localhost
##    port: 587
#    port : 1025 # MailHog 같은 개발용 STMP 서버 포트
#    username: test@gmail.com
#    password: test1234!
#    properties:
#      mail:
#        smtp:
#          auth: false
#          starttls:
#            enable: false